### ISSUE TITLE
Google Closure Version Compatibility?

### ISSUE THREAD

**Issue by parkr** [robfig/soy#23]
Hey!

I noticed that some syntax that the Google Closure examples had weren't compiling with this library. What features does this library lack? Is it meant to conform only with one version of Closure?

**Comment by robfig** [comment]
I haven't had a chance to update this library for some of the new features released last April (mostly strong typing of params and strict autoescaping).   Which example does not work?

**Comment by parkr** [comment]
It was mostly the strong typing of params that we were looking for. :smiley:

**Comment by robfig** [comment]
Yep, afraid you have to use the old syntax for now.  Pull requests welcome :)
