### ISSUE TITLE
single param not rendering

### ISSUE THREAD

**Issue by bsferrazza** [robfig/soy#28]
Perhaps I'm doing something wrong, but when I try rendering a soy template with a single param, it results in an empty bytes.Buffer. A template with more than one param (e.g. two) or none works fine.

```go
// no param works
tofu.Render(resp, "acme.account.noparam", nil)

// two params work
var obj = map[string]interface{}{
  "user":    user,
  "account": account,
}
tofu.Render(resp, "acme.account.twoparams", obj)

// one param doesn't work
var obj2 = map[string]interface{}{
  "user":    user,
}
tofu.Render(resp, "acme.account.oneparam", obj2)

**Comment by robfig** [comment]
Check the error being returned. What does it say?

**Comment by bsferrazza** [comment]
I apologize for the false alarm. I don't think I had saved my soy template file after updating the param registry at the top of the file, because it worked just fine when I tried rerunning it.
