### ISSUE TITLE
i18n vs master?

### ISSUE THREAD

**Issue by mhupman** [robfig/soy#61]
Of the recent merged PRs, some are merged into master and others into i18n.  Is there a preferred target?  Is there a reason i18n needs to remain out of master or can we consider merging them and using master moving forward?  cc @theothertomelliott @angelaxu1

**Comment by robfig** [comment]
Merging them sounds pretty great. I imagine they were separate to isolate master from the development, and there was no finish line for when to merge them.

Are there any backwards incompatible changes?

**Comment by mhupman** [comment]
Handled in #63
