### ISSUE TITLE
Ineffective assignment in soy/parse/rawtext.go:84

### ISSUE THREAD

**Issue by mbrukman** [robfig/soy#78]
According to the [Go Report Card](https://goreportcard.com/report/github.com/robfig/soy#ineffassign):

> [IneffAssign](https://github.com/gordonklaus/ineffassign) detects ineffectual assignments in Go code.
> [`soy/parse/rawtext.go`
> Line 84][rawtext-L84]: warning: ineffectual assignment to seenNewline (ineffassign)

The code looks as follows:

> ```go
> if spaces > 0 {
>   // ... skipped
>   seenNewline = false   // Line 84
> }
>
> // begin to trim
> seenNewline = isEndOfLine(r)

As you can see, the very next statement outside of the `if` block is overwriting the vlaue of `seenNewline` so this assignment is correctly marked as ineffectual. Thus, it is either a bug (this line should be removed) or there should have been something else there that depends on the value of `seenNewline` within the `if` block, before it exits and is overwritten immediately afterwards.

Thoughts, @robfig?

[rawtext-L84]: https://github.com/robfig/soy/blob/925ddfcf8d6ac6b2c965d691457a01b179f505b1/parse/rawtext.go#L84

**Comment by robfig** [comment]
Good find -- I agree that the assignment on line 84 could be removed. I don't believe anything else should have been there; it's just updating a bit related to the whitespace-skipping mechanism to reflect the latest state, but that bit is not needed. Fine to remove, thanks.
