### ISSUE TITLE
Replace Travis CI with GitHub Actions

### ISSUE THREAD

**Issue by mbrukman** [robfig/soy#85]
Looking at https://travis-ci.org/github/robfig/soy, the last time it ran was over 2 years ago, so this project is currently without automatic testing for new PRs.

Additionally, there's a message at the top of the page:

> Since June 15th, 2021, the building on [travis-ci.org](http://www.travis-ci.org/) is ceased. Please use [travis-ci.com](http://www.travis-ci.com/) from now on.

Would you be open to converting the Travis CI config for this project to GitHub Actions?

Should be pretty straight-forward, happy to help with this. In fact, looking at the history, looks like I made the last change to the [`.travis.yml`](https://github.com/robfig/soy/commits/master/.travis.yml) config file, over 2 years ago now (!) anyway. :-)

**Comment by robfig** [comment]
Hah, please do thank you
